language: go
env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=linux GIMME_ARCH=386
go:
  - 1.6
  - 1.7
script: go test -v -coverprofile=coverage.txt -covermode=atomic -bench .
after_success:
  - bash <(curl -s https://codecov.io/bash)
